### PR TITLE
Refactor tags code into new inc file

### PR DESCRIPTION
**Pull request by JBKingdon**
I created layoutTag.inc to contain the common code for creating Eep_ESC_Layout and Eep_ESC_MCU. This should make it much easier if we need to add addition DT values or make other changes to the tags.

I like the idea of having extra information in the layout tag eg for PWM and to identify the fork of BLHeli_s being used, but this would force the user to check the 'ignore mismatched layout' checkbox and would likely cause problems. I've put the support for adding pwm to the tag in the new inc file, controlled by a new symbol. After applying this change you will need to set

USE_EXTENDED_LAYOUT = 0

to suppress the new format, or set it to 1 to use the extended format with pwm info.

### CODE REVIEW

**Comment by JBKingdon** [comment]
I'm a bit worried about the merge commit that this has picked up. My git skills aren't that great - I tried to rebase my changes on the latest version of your branch and ended up with the extra commit. Hopefully it doesn't cause any problems when you merge.

**Comment by JazzMaverick** [comment]
now they are all clean and easy. Great!

**Comment by JazzMaverick** [comment]
can use DT_tens to replace USE_EXTENDED_LAYOUT ?

**Comment by JBKingdon** [comment]
> can use DT_tens to replace USE_EXTENDED_LAYOUT ?

Hmm, I don't think so. USE_EXTENDED_LAYOUT adds the PWM frequency to the end of the tag. It's nice to be able to see the PWM freq when you read the ESC from the configurator, but it makes it harder for the users because they then have to click the "ignore incorrect mcu/layout" check box when flashing, so I put the flag in so that we could use normal layout for releases and extended layout during development (or for people like me who have too many ESCs and forget which ones have which settings).

**Comment by JazzMaverick** [comment]
Sorry, my bad. fix my question as below:

Now can only use USE_EXTENDED_LAYOUT = 0
Modify blheli configurator to support USE_EXTENDED_LAYOUT=1, right?

**Comment by JBKingdon** [comment]
Yes, if we could get blheli configurator modified so that only the first part of the tag was checked and anything after the DT was ignored that would make life a lot easier. We can still use USE_EXTENDED_LAYOUT=1 now for our own use, just have to be careful not to flash the wrong file.

**Comment by bernatalbet** [comment]
Hi,
I've downloaded the latest code and compile it, but I got an assembly error. After looking at the LST file, I saw the problem of the USE_EXTENDED_LAYOUT issue, and I've found this thread. Maybe you could modify the MakeHexFiles.bat file to include the DEFINE(USE_EXTENDED_LAYOUT=0), just to save some time to the next person who found the same situation :)

Thanks!

**Comment by JBKingdon** [comment]
Hi, sorry about that @bernatalbet . I don't run windows so can't test any changes I make to the bat file and thought it best to leave it alone. Would you be able to submit a PR with the change?

**Comment by bernatalbet** [comment]
Sorry I'm not familiarized with GIT yet, I'm more a SVN guy :P  Just wanted to note that without defining the USE_EXTENDED_LAYOUT it doesn't compile (I guess regardless of using windows or linux). BTW, I know it's off topic, but I made an excel to calculate the values of all the delays to generate any note from G3 to C6 (including sharps and flat notes) for the blheli_s. Of course, the startup melody was written directly in assembler, but if you never plan to do something similar to the blheli 32, you will already have this part done ;)
Thanks!

**Pull request merged**
